=== MatousJobanek/arquillian-rusheye/src/main/resources/visual-suite.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
JBoss, Home of Professional Open Source
Copyright 2010, Red Hat, Inc. and individual contributors
by the @authors tag. See the copyright.txt in the distribution for a
full listing of individual contributors.


This is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License as
published by the Free Software Foundation; either version 2.1 of
the License, or (at your option) any later version.


This software is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.


You should have received a copy of the GNU Lesser General Public
License along with this software; if not, write to the Free
Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
02110-1301 USA, or see the FSF site: http://www.fsf.org.

@author <a href="mailto:lfryc@redhat.com">Lukas Fryc</a>
@version $Revision$

-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.jboss.org/test/visual-suite" xmlns:tns="http://www.jboss.org/test/visual-suite"
	xmlns:vs="http://www.jboss.org/test/visual-suite" elementFormDefault="qualified"
	version="1.0">

	<xs:element name="visual-suite">
		<xs:annotation>
			<xs:documentation>Visual Suite, the base of visual test configuration
			</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="global-configuration" type="vs:ConfigurationType" />
				<xs:element name="test" type="vs:TestType" maxOccurs="unbounded">
					<xs:unique name="TestMasksMaskIdUnique">
						<xs:annotation>
							<xs:documentation>Mask ID have to be unique across all particular tests
							</xs:documentation>
						</xs:annotation>
						<xs:selector xpath="vs:masks/vs:mask" />
						<xs:field xpath="@id" />
					</xs:unique>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="id" type="xs:integer" />
		</xs:complexType>
		<xs:unique name="TestNameUnique">
			<xs:annotation>
				<xs:documentation>Test name must be unique across the suite
				</xs:documentation>
			</xs:annotation>
			<xs:selector xpath="vs:test" />
			<xs:field xpath="@name" />
		</xs:unique>
		<xs:unique name="TestPatternNameUnique">
			<xs:annotation>
				<xs:documentation>Pattern name must be unique across the suite
					(implies uniqueness across all tests and patterns)
				</xs:documentation>
			</xs:annotation>
			<xs:selector xpath="vs:test/vs:pattern" />
			<xs:field xpath="@name" />
		</xs:unique>
		<xs:unique name="MasksMaskIdUnique">
			<xs:annotation>
				<xs:documentation>Mask ID have to be unique across global configuration
				</xs:documentation>
			</xs:annotation>
			<xs:selector xpath="vs:global-configuration/vs:masks/vs:mask" />
			<xs:field xpath="@id" />
		</xs:unique>
	</xs:element>

	<xs:complexType name="ConfigurationType">
		<xs:annotation>
			<xs:documentation>Configuration of suite including images and masks
				retrieving and global perception settings</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="image-retriever" type="vs:ImageRetrieverType"
				minOccurs="0" />
			<xs:element name="mask-retriever" type="vs:MaskRetrieverType"
				minOccurs="0" />
			<xs:element name="perception" type="vs:PerceptionType"
				minOccurs="0" />
			<xs:element name="masks" type="vs:MasksType" minOccurs="0"
				maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="MasksType">
		<xs:annotation>
			<xs:documentation>List of masks of given type </xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="mask" minOccurs="1" maxOccurs="unbounded">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="vs:SourceType">
							<xs:attribute name="id" type="xs:Name" use="required" />
							<xs:attribute name="vertical-align" type="vs:VerticalAlignType"
								use="optional" />
							<xs:attribute name="horizontal-align" type="vs:HorizontalAlignType"
								use="optional" />
						</xs:extension>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="type" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="selective-alpha" />
					<xs:enumeration value="ignore-bitmap" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>

	<xs:simpleType name="VerticalAlignType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="top" />
			<xs:enumeration value="bottom" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="HorizontalAlignType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="left" />
			<xs:enumeration value="right" />
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="ImageRetrieverType">
		<xs:complexContent>
			<xs:extension base="vs:RetrieverPropertiesType">
				<xs:attribute name="class" type="vs:RetrieverClassType" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="MaskRetrieverType">
		<xs:complexContent>
			<xs:extension base="vs:RetrieverPropertiesType">
				<xs:attribute name="class" type="vs:RetrieverClassType" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:simpleType name="RetrieverClassType">
		<xs:restriction base="xs:string">
			<xs:minLength value="1" />
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="RetrieverPropertiesType">
		<xs:sequence>
			<xs:any minOccurs="0" maxOccurs="unbounded" processContents="lax" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="PerceptionType">
		<xs:sequence>
			<xs:element name="one-pixel-treshold" type="vs:ColorTresholdType"
				minOccurs="0" />
			<xs:element name="global-difference-treshold" type="vs:ColorTresholdType"
				minOccurs="0" />
			<xs:element name="global-difference-pixel-amount" type="vs:SizeType"
				minOccurs="0" />
		</xs:sequence>
	</xs:complexType>

	<xs:simpleType name="ColorTresholdType">
		<xs:restriction base="xs:nonNegativeInteger">
			<xs:maxExclusive value="768" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="SizeType">
		<xs:union memberTypes="vs:PercentSizeType vs:PixelSizeType" />
	</xs:simpleType>

	<xs:simpleType name="PercentSizeType">
		<xs:restriction base="xs:string">
			<xs:pattern value="([0-9]{1,2}|100)%" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="PixelSizeType">
		<xs:restriction base="xs:string">
			<xs:pattern value="\d+px" />
		</xs:restriction>
	</xs:simpleType>


	<xs:complexType name="TestType">
		<xs:sequence>
			<xs:element name="perception" type="vs:PerceptionType"
				minOccurs="0" />
			<xs:element name="masks" type="vs:MasksType" minOccurs="0"
				maxOccurs="unbounded" />
			<xs:element name="pattern" type="vs:TestPatternType"
				maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="name" type="xs:Name" use="required" />
	</xs:complexType>

	<xs:complexType name="TestPatternType">
		<xs:complexContent>
			<xs:extension base="vs:SourceType">
				<xs:attribute name="name" type="xs:Name" use="required" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="SourceType">
		<xs:sequence>
			<xs:any minOccurs="0" maxOccurs="unbounded" processContents="lax" />
		</xs:sequence>
		<xs:attribute name="source">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"></xs:minLength>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
</xs:schema>

=== MatousJobanek/arquillian-rusheye/src/test/resources/parser-input/configuration.xml
<visual-suite xmlns="http://www.jboss.org/test/visual-suite"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.jboss.org/test/visual-suite ../../main/resources/visual-suite.xsd">

	<global-configuration>
		<!-- the image retriever, implementing SourceRetriever interface -->
		<image-retriever class="org.jboss.lupic.retriever.FileRetriever">
			<xxx></xxx>
			<yyy></yyy>
		</image-retriever>
		<perception>
			<!--
				unperceptible treshold of color difference in scope of one pixel
			-->
			<!-- 0-768 -->
			<one-pixel-treshold>5</one-pixel-treshold>
			<!--
				unperceptible treshold of color difference of one pixel to be
				recognized as perceptible difference in global image scope
			-->
			<!-- 0-768 -->
			<global-difference-treshold>10</global-difference-treshold>
			<!-- amount of pixels perceptually different -->
			<!-- % of image surface / 0-* of pixels differ  -->
			<global-difference-pixel-amount>1%</global-difference-pixel-amount>
		</perception>
		<masks type="ignore-bitmap">
			<mask id="xxx" source="xxx.png" />
		</masks>
		<masks type="selective-alpha">
			<mask id="yyy" source="yyy.png" vertical-align="bottom" />
		</masks>
	</global-configuration>
</visual-suite>

=== MatousJobanek/arquillian-rusheye/src/test/resources/visual-suite.example.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
JBoss, Home of Professional Open Source
Copyright 2010, Red Hat, Inc. and individual contributors
by the @authors tag. See the copyright.txt in the distribution for a
full listing of individual contributors.


This is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License as
published by the Free Software Foundation; either version 2.1 of
the License, or (at your option) any later version.


This software is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.


You should have received a copy of the GNU Lesser General Public
License along with this software; if not, write to the Free
Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
02110-1301 USA, or see the FSF site: http://www.fsf.org.

@author <a href="mailto:lfryc@redhat.com">Lukas Fryc</a>
@version $Revision$

-->
<visual-suite xmlns="http://www.jboss.org/test/visual-suite"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.jboss.org/test/visual-suite ../../main/resources/visual-suite.xsd">

	<global-configuration>
		<!-- the image retriever, implementing SourceRetriever interface -->
		<image-retriever class="org.jboss.visualTesting.FileSourceRetriever">
			<xxx></xxx>
			<yyy></yyy>
		</image-retriever>
		<mask-retriever class="org.jboss.visualTesting.FileSourceRetriever" />
		<perception>
			<!--
				unperceptible treshold of color difference in scope of one pixel
			-->
			<!-- 0-768 -->
			<one-pixel-treshold>5</one-pixel-treshold>
			<!--
				unperceptible treshold of color difference of one pixel to be
				recognized as perceptible difference in global image scope
			-->
			<!-- 0-768 -->
			<global-difference-treshold>10</global-difference-treshold>
			<!-- amount of pixels perceptually different -->
			<!-- % of image surface / 0-* of pixels differ  -->
			<global-difference-pixel-amount>1%</global-difference-pixel-amount>
		</perception>
		<masks type="ignore-bitmap">
			<mask id="xxx" source="xxx.png" />
		</masks>
		<masks type="selective-alpha">
			<mask id="yyy" source="yyy.png" vertical-align="bottom" />
		</masks>
	</global-configuration>

	<test name="AjaxSupportTestCase.testEmpty">
		<masks type="ignore-bitmap">
			<mask id="xxx" source="xxx.png" />
		</masks>
		<pattern name="AjaxSupportTestCase.testEmpty.1" source="AjaxSupportTestCase.testEmpty.1.png" />
		<pattern name="AjaxSupportTestCase.testEmpty.2" source="AjaxSupportTestCase.testEmpty.2.png" />
	</test>

	<test name="BeanValidatorTestCase.testAgeIntegerOnly:168">
		<perception>
			<global-difference-pixel-amount>10px</global-difference-pixel-amount>
		</perception>
		<pattern name="BeanValidatorTestCase.testAgeIntegerOnly:168.1">
			<xxx>BeanValidatorTestCase.testAgeIntegerOnly:168.png</xxx>
			<yyy>10</yyy>
		</pattern>
	</test>
</visual-suite>
