=== MatousJobanek/arquillian-rusheye/src/main/resources/visual-suite-result.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.jboss.org/test/visual-suite-result"
	xmlns:tns="http://www.jboss.org/test/visual-suite-result" xmlns:vsr="http://www.jboss.org/test/visual-suite-result"
	elementFormDefault="qualified" version="1.0">

	<xs:element name="visual-suite-result">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="test" type="vsr:TestType" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
		<xs:unique name="TestNameUnique">
			<xs:selector xpath="vsr:test" />
			<xs:field xpath="@name" />
		</xs:unique>
		<xs:unique name="TestPatternNameUnique">
			<xs:selector xpath="vsr:test/vsr:pattern" />
			<xs:field xpath="@name" />
		</xs:unique>
	</xs:element>

	<xs:complexType name="TestType">
		<xs:sequence>
			<xs:element name="pattern" type="vsr:PatternType" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:Name" use="required" />
	</xs:complexType>

	<xs:complexType name="PatternType">
		<xs:sequence>
			<xs:element name="perception" type="vsr:PerceptionType"
				minOccurs="0" />
			<xs:element name="error-output" type="xs:string"
				minOccurs="0" />
		</xs:sequence>
		<xs:attribute name="name" type="xs:Name" use="required" />
		<xs:attribute name="result" type="vsr:ResultType" use="required" />
		<xs:attribute name="output" type="xs:string" />
	</xs:complexType>

	<xs:simpleType name="ResultType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="same" />
			<xs:enumeration value="perceptually-same" />
			<xs:enumeration value="differ" />
			<xs:enumeration value="error" />
			<xs:enumeration value="not-tested" />
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="PerceptionType">
		<xs:sequence>
			<xs:element name="area" type="vsr:AreaType" />
			<xs:element name="rectangle" type="vsr:RectangleType" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="total-pixels" type="vsr:PixelAmountType" />
			<xs:element name="masked-pixels" type="vsr:PixelAmountType" />
			<xs:element name="perceptible-different-pixels" type="vsr:PixelAmountType" />
			<xs:element name="global-different-pixels" type="vsr:PixelAmountType" />
			<xs:element name="unperceptible-different-pixels" type="vsr:PixelAmountType" />
			<xs:element name="same-pixels" type="vsr:PixelAmountType" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="AreaType">
		<xs:attribute name="width" type="xs:nonNegativeInteger" use="required" />
		<xs:attribute name="height" type="xs:nonNegativeInteger" use="required" />
	</xs:complexType>
	
	<xs:complexType name="RectangleType">
		<xs:sequence>
			<xs:element name="vertex" minOccurs="2" maxOccurs="2">
				<xs:complexType>
					<xs:attribute name="x" type="xs:nonNegativeInteger" use="required" />
					<xs:attribute name="y" type="xs:nonNegativeInteger" use="required" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:simpleType name="PixelAmountType">
		<xs:restriction base="xs:nonNegativeInteger" />
	</xs:simpleType>
</xs:schema>

=== MatousJobanek/arquillian-rusheye/src/test/resources/visual-suite-result.example.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
JBoss, Home of Professional Open Source
Copyright 2010, Red Hat, Inc. and individual contributors
by the @authors tag. See the copyright.txt in the distribution for a
full listing of individual contributors.


This is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License as
published by the Free Software Foundation; either version 2.1 of
the License, or (at your option) any later version.


This software is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.


You should have received a copy of the GNU Lesser General Public
License along with this software; if not, write to the Free
Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
02110-1301 USA, or see the FSF site: http://www.fsf.org.
-->
<visual-suite-result xmlns="http://www.jboss.org/test/visual-suite-result"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.jboss.org/test/visual-suite-result ../../main/resources/visual-suite-result.xsd">
		
	<test name="AjaxSupportTestCase.testEmpty">
		<pattern name="p10" result="differ" output="diffs/AjaxSupportTestCase.testEmpty.1.png">
			<perception>
				<area width="558" height="1145" />
				<rectangle>
					<vertex x="0" y="5" />
					<vertex x="10" y="140" />
				</rectangle>
				<total-pixels>5</total-pixels>
				<masked-pixels>15</masked-pixels>
				<perceptible-different-pixels>345</perceptible-different-pixels>
				<global-different-pixels>53</global-different-pixels>
				<unperceptible-different-pixels>2345</unperceptible-different-pixels>
				<same-pixels>3245</same-pixels>
			</perception>
		</pattern>
		<pattern name="p1" result="same" />
		<pattern name="p2" result="not-tested" />
	</test>
	<test name="BeanValidatorTestCase.testAgeIntegerOnly:168">
		<pattern name="p3" result="differ" />
		<pattern name="p4" result="differ" />
		<pattern name="p5" result="differ" />
	</test>
	<test name="xxx">
		<pattern name="p6" result="perceptually-same" />
		<pattern name="p7" result="not-tested" />
		<pattern name="p8" result="not-tested" />
	</test>
	<test name="yyy">
		<pattern name="p9" result="error" />
		<pattern name="p11" result="same" />
	</test>
</visual-suite-result>

=== MatousJobanek/arquillian-rusheye/rusheye-impl/src/test/resources/visual-suite-result.example.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    JBoss, Home of Professional Open Source
    Copyright ${year}, Red Hat, Inc. and individual contributors
    by the @authors tag. See the copyright.txt in the distribution for a
    full listing of individual contributors.

    This is free software; you can redistribute it and/or modify it
    under the terms of the GNU Lesser General Public License as
    published by the Free Software Foundation; either version 2.1 of
    the License, or (at your option) any later version.

    This software is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
    Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public
    License along with this software; if not, write to the Free
    Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
    02110-1301 USA, or see the FSF site: http://www.fsf.org.

-->
<visual-suite-result xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="http://www.jboss.org/test/visual-suite-result"
    xsi:schemaLocation="http://www.jboss.org/test/visual-suite-result ../../main/resources/visual-suite-result.xsd">

  <test name="AjaxSupportTestCase.testEmpty">
    <pattern name="p1" result="DIFFER"
        output="diffs/AjaxSupportTestCase.testEmpty.1.png">
      <comparison-result>
        <area width="558" height="1145"/>
        <rectangle>
          <point x="0" y="5"/>
          <point x="10" y="140"/>
        </rectangle>
        <total-pixels>5</total-pixels>
        <masked-pixels>15</masked-pixels>
        <perceptible-different-pixels>345</perceptible-different-pixels>
        <global-different-pixels>53</global-different-pixels>
        <unperceptible-different-pixels>2345</unperceptible-different-pixels>
        <same-pixels>3245</same-pixels>
      </comparison-result>
    </pattern>
    <pattern name="p2" result="SAME"/>
    <pattern name="p3" result="NOT_TESTED"/>
  </test>
  <test name="BeanValidatorTestCase.testAgeIntegerOnly:168">
    <pattern name="p4" result="DIFFER"/>
    <pattern name="p5" result="DIFFER"/>
    <pattern name="p6" result="DIFFER"/>
  </test>
  <test name="xxx">
    <pattern name="p7" result="PERCEPTUALLY_SAME"/>
    <pattern name="p8" result="NOT_TESTED"/>
    <pattern name="p9" result="NOT_TESTED"/>
  </test>
  <test name="yyy">
    <pattern name="p10" result="ERROR">
      <error-output>Stack trace...</error-output>
    </pattern>
    <pattern name="p11" result="SAME"/>
  </test>
</visual-suite-result>
